version: "3.8"
services:

  backend:
    build: .

    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
        - POSTGRES_DBNAME=admin
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root









